# Generated by Django 5.0.7 on 2024-08-05 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rece", "0004_subject_subjectmarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_created=True)),
                ("student_rank", models.IntegerField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentmarks",
                        to="rece.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student_rank", "date")},
            },
        ),
    ]
