# Generated by Django 5.0.7 on 2024-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rece", "0005_studentrank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrank",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
