# Generated by Django 5.0.7 on 2024-08-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rece", "0006_alter_studentrank_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
